#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
dunst &
pgrep bspswallow || bspswallow &
feh --bg-fill ~/Pictures/wallpapers/astronaut-jellyfish.jpg &
~/.config/polybar/forest/launch.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         0
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colors
bspc config active_border_color     "#474f54"
bspc config focused_border_color    "#474f54"
bspc config normal_border_color     "#373d41"
bspc config presel_feedback_color   "#373d41"

# Rules
bspc rule -a firefox desktop=2
bspc rule -a discord desktop=4 follow=on
bspc rule -a spotify dekstop=9 follow=on
